apiVersion: 1

deleteDatasources:
 - name: 'InfluxDB'

datasources:
 - name: 'InfluxDB'
   type: 'influxdb'
   url: 'http://influx:8086'
   database: 'fitbit-data'
   version: 1
   access: 'proxy'
   jsonData:
     httpMode: 'GET'
